# Generated by Django 4.1.4 on 2023-08-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_logout", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
